version: "3"
services:
  postgres:
    image: postgres
    env_file: .env

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    command: python main.py
    restart: on-failure
    env_file: .env

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    command: node server.js
    restart: on-failure
    env_file: .env

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
